name: test

on:
  push:
    branches: [main]
    paths-ignore: [README.md, .cspell.json, .gitignore, imgs/**]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check code
        run: make check

      - name: Test code
        run: make test
